/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jedisprueba;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import redis.clients.jedis.Jedis;

/**
 *
 * @author euced
 */
public class ProyectoTBDD2 extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoTBDD2
     */
    ArrayList<String> users = new ArrayList();
    ArrayList<String> id = new ArrayList();

    public ProyectoTBDD2() {
        initComponents();
        tf_usuarioL.setText("Admin");
        pf_contraL.setText("admin1234");

//        Jedis jedis = new Jedis("localhost", 6379);
//        Set<String> names = jedis.keys("*");
//
//        java.util.Iterator<String> it = names.iterator();
//        while (it.hasNext()) {
//            String s = it.next();
//            users.add(s + "+" + jedis.get(s));
//            id.add(s);
//        }
//
//        tokenizarAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registrar = new javax.swing.JDialog();
        tf_nameR = new javax.swing.JTextField();
        tf_loginR = new javax.swing.JTextField();
        pf_passR = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_registrarR = new javax.swing.JButton();
        jb_regresarR = new javax.swing.JButton();
        jd_login = new javax.swing.JDialog();
        tf_usuarioL = new javax.swing.JTextField();
        pf_contraL = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jb_loginL = new javax.swing.JButton();
        jb_regresarL = new javax.swing.JButton();
        jd_estudiante = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jd_admin = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tf_idClaseC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreClaseC = new javax.swing.JTextField();
        cb_clasesC = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jb_crearClase = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cb_elegirClase = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jl_cantPreguntas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_idPregunta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_descripcion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cb_respuesta = new javax.swing.JComboBox<>();
        jb_crearPregunta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cb_elegirClaseE = new javax.swing.JComboBox<>();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jb_login = new javax.swing.JButton();
        jb_registrar = new javax.swing.JButton();

        jd_registrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_registrar.getContentPane().add(tf_nameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 120, -1));
        jd_registrar.getContentPane().add(tf_loginR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 120, -1));
        jd_registrar.getContentPane().add(pf_passR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, -1));

        jLabel1.setText("Nombre completo");
        jd_registrar.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel2.setText("Login");
        jd_registrar.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel3.setText("Contraseña");
        jd_registrar.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jb_registrarR.setText("Registrar");
        jb_registrarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarRMouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jb_registrarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jb_regresarR.setText("Regresar");
        jb_regresarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarRMouseClicked(evt);
            }
        });
        jd_registrar.getContentPane().add(jb_regresarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jd_login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_login.getContentPane().add(tf_usuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 140, 30));
        jd_login.getContentPane().add(pf_contraL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 140, 30));

        jLabel4.setText("Nombre de Usuario");
        jd_login.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabel5.setText("Contraseña");
        jd_login.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jb_loginL.setText("Ingresar");
        jb_loginL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginLMouseClicked(evt);
            }
        });
        jd_login.getContentPane().add(jb_loginL, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jb_regresarL.setText("Regresar");
        jb_regresarL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarLMouseClicked(evt);
            }
        });
        jd_login.getContentPane().add(jb_regresarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jd_estudiante.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("holap");
        jd_estudiante.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 264, -1, -1));

        jd_admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_idClaseC.setEditable(false);
        jPanel2.add(tf_idClaseC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 30));

        jLabel7.setText("IdClase");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel9.setText("Nombre Clase");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel2.add(tf_nombreClaseC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, 30));

        cb_clasesC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel2.add(cb_clasesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 180, 30));

        jLabel10.setText("Clases Creadas");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jb_crearClase.setText("Crear Clase");
        jb_crearClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearClaseMouseClicked(evt);
            }
        });
        jPanel2.add(jb_crearClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 30));

        jTabbedPane1.addTab("Crear Clase", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Elija una clase");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        cb_elegirClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clases Creadas" }));
        cb_elegirClase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_elegirClaseItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_elegirClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 180, 40));

        jLabel11.setText("Cantidad de preguntas que tiene esta clase");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jl_cantPreguntas.setText("#");
        jPanel3.add(jl_cantPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 20, -1));

        jLabel13.setText("Id de Pregunta");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        tf_idPregunta.setEditable(false);
        jPanel3.add(tf_idPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 110, 30));

        jLabel14.setText("Titulo");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));
        jPanel3.add(tf_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 170, 40));

        jLabel15.setText("Descripcion");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));
        jPanel3.add(tf_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 170, 40));

        jLabel16.setText("Respuesta");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        cb_respuesta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verdadero", "Falso" }));
        jPanel3.add(cb_respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 120, 30));

        jb_crearPregunta.setText("Crear Pregunta");
        jb_crearPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearPreguntaMouseClicked(evt);
            }
        });
        jPanel3.add(jb_crearPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 130, 30));

        jTabbedPane1.addTab("Crear Pregunta", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_elegirClaseE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clases Creadas" }));
        cb_elegirClaseE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_elegirClaseEItemStateChanged(evt);
            }
        });
        jPanel4.add(cb_elegirClaseE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 180, 40));
        jPanel4.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel12.setText("jLabel12");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel17.setText("jLabel17");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jTextField1.setText("jTextField1");
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 30));

        jTabbedPane1.addTab("Crear Examen", jPanel4);

        jd_admin.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_login.setText("Login");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });
        jPanel1.add(jb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jb_registrar.setText("Registrate");
        jb_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarMouseClicked(evt);
            }
        });
        jPanel1.add(jb_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarMouseClicked
        // TODO add your handling code here:
        jd_registrar.pack();
        jd_registrar.setLocationRelativeTo(null);
        jd_registrar.setVisible(true);
    }//GEN-LAST:event_jb_registrarMouseClicked

    private void jb_regresarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarRMouseClicked
        // TODO add your handling code here:
        jd_registrar.setVisible(false);
    }//GEN-LAST:event_jb_regresarRMouseClicked

    private void jb_registrarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarRMouseClicked
        // TODO add your handling code here:

        if (tf_nameR.getText().isEmpty() || tf_loginR.getText().isEmpty() || pf_passR.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            Jedis jedis = new Jedis("localhost", 6379);

            Set<String> names = jedis.keys("*");
            java.util.Iterator<String> it = names.iterator();
            boolean validar = false;
            String s = "";
            int pos = 1000;

            while (it.hasNext()) {
                s = it.next();

                HashMap<String, String> val = (HashMap<String, String>) jedis.hgetAll(s);

                //System.out.println("todo "+jedis.hgetAll(s));
                if (Integer.parseInt(s) >= 101 && Integer.parseInt(s) <= 1000) {
                    pos--;
                    if (val.get("login").equals(tf_loginR.getText())) {
                        validar = true;
                        break;
                    }
                }

            }

            if (validar == true) {
                JOptionPane.showMessageDialog(null, "Ya existe un usuario con ese login");
            } else {
                int idE = pos;
                String tide = idE + "";
                //String cadena = tf_nameR.getText() + "+" + tf_loginR.getText() + "+" + pf_passR.getText();
                //subirBase(idE, cadena);

                HashMap<String, String> examen = new HashMap<>();
                examen.put("Nombre ", tf_nameR.getText());
                examen.put("login", tf_loginR.getText());
                examen.put("Contrasena", pf_passR.getText());

                jedis.hmset(tide, examen);

                JOptionPane.showMessageDialog(null, "Estudiante creado con exito");
                tf_nameR.setText("");
                tf_loginR.setText("");
                pf_passR.setText("");
            }

        }
    }//GEN-LAST:event_jb_registrarRMouseClicked

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:
        jd_login.pack();
        jd_login.setLocationRelativeTo(null);
        jd_login.setVisible(true);
    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_regresarLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarLMouseClicked
        // TODO add your handling code here:
        jd_login.setVisible(false);
    }//GEN-LAST:event_jb_regresarLMouseClicked

    private void jb_loginLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginLMouseClicked
        // TODO add your handling code here:
        cb_clasesC.setModel(new DefaultComboBoxModel());
        cb_elegirClase.setModel(new DefaultComboBoxModel());
        cb_elegirClaseE.setModel(new DefaultComboBoxModel());

        boolean validar = false;
        boolean validarAdmin = false;
        int contClases = 1;
        if (tf_usuarioL.getText().isEmpty() || pf_contraL.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {

            Jedis jedis = new Jedis("localhost", 6379);

            Set<String> names = jedis.keys("*");
            java.util.Iterator<String> it = names.iterator();
            String s = "";
            int pos = 1001;

            while (it.hasNext()) {
                int igual = 0;
                int igual2 = 0;
                s = it.next();
                List<String> todo = jedis.hvals(s);
                Set<String> llaves = jedis.hkeys(s);

                Iterator<String> i = llaves.iterator();
                int cont = 0;
                while (i.hasNext()) {
                    String next = i.next();
                    if (next.equals("login")) {
                        igual = cont;

                    }

                    if (next.equals("Contrasena")) {
                        igual2 = cont;

                    }
                    cont++;
                }

                if (Integer.parseInt(s) >= 101 && Integer.parseInt(s) <= 1000) {
                    pos--;

                    //if (todo.get(igual).equals(tf_loginR.getText())) {
                    if (tf_usuarioL.getText().equals("Admin") && pf_contraL.getText().equals("admin1234")) {
                        validarAdmin = true;
                    }
                    if (todo.get(igual).equals(tf_usuarioL.getText()) && todo.get(igual2).equals(pf_contraL.getText())) {

                        validar = true;

                        break;
                    }
                } else if (Integer.parseInt(s) >= 1 && Integer.parseInt(s) <= 100) {
                    cb_clasesC.addItem("ID: " + s + " : " + jedis.hgetAll(s));
                    cb_elegirClase.addItem("ID: " + s + " : " + jedis.hgetAll(s));
                    cb_elegirClaseE.addItem("ID: " + s + " : " + jedis.hgetAll(s));
                    contClases++;
                }

            }

//            for (int i = 0; i < alumnos.size(); i++) {
//                if (alumnos.get(i).getLogin().equals(tf_usuarioL.getText()) && alumnos.get(i).getPassword().equals(pf_contraL.getText())) {
//                    if (tf_usuarioL.getText().equals("Admin") && pf_contraL.getText().equals("admin1234")) {
//                        validarAdmin = true;
//                    } else {
//                        validar = true;
//
//                    }
//                }
//            }
            if (validar == true) {

                jd_login.setVisible(false);
                jd_estudiante.pack();
                jd_estudiante.setLocationRelativeTo(null);
                jd_estudiante.setVisible(true);
            } else if (validarAdmin == true) {

                tf_idClaseC.setText(contClases + "");
                jd_login.setVisible(false);
                jd_admin.pack();
                jd_admin.setLocationRelativeTo(null);
                jd_admin.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta");
            }
            tf_usuarioL.setText("");
            pf_contraL.setText("");
        }
    }//GEN-LAST:event_jb_loginLMouseClicked

    private void jb_crearClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearClaseMouseClicked
        // TODO add your handling code here:
        if (tf_nombreClaseC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            Jedis jedis = new Jedis("localhost", 6379);

            Set<String> names = jedis.keys("*");
            java.util.Iterator<String> it = names.iterator();
            boolean validar = false;
            String s = "";
            int cuenta = 1;
            while (it.hasNext()) {
                s = it.next();
                List<String> todo = jedis.hvals(s);

                if (Integer.parseInt(s) >= 1 && Integer.parseInt(s) <= 100) {
                    cuenta++;
                    if (todo.get(0).equals(tf_nombreClaseC.getText())) {
                        validar = true;
                        break;
                    }
                }

            }

            if (validar) {
                JOptionPane.showMessageDialog(null, "Ya existe una clase con ese nombre");
            } else {
                HashMap<String, String> examen = new HashMap<>();
                examen.put("NombreClase", tf_nombreClaseC.getText());

                jedis.hmset(cuenta + "", examen);
                cb_clasesC.addItem("ID: " + cuenta + " : " + examen);
                cb_elegirClase.addItem("ID: " + cuenta + " : " + examen);
                cb_elegirClaseE.addItem("ID: " + cuenta + " : " + examen);
                
                JOptionPane.showMessageDialog(null, "Clase creada con exito");
            }
            tf_nombreClaseC.setText("");
        }

    }//GEN-LAST:event_jb_crearClaseMouseClicked

    private void jb_crearPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearPreguntaMouseClicked
        // TODO add your handling code here:

        if (tf_titulo.getText().isEmpty() || tf_descripcion.getText().isEmpty() || cb_elegirClase.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            Jedis jedis = new Jedis("localhost", 6379);

            Set<String> names = jedis.keys("*");
            java.util.Iterator<String> it = names.iterator();
            boolean validar = false;
            String s = "";
            int cuenta = 2001;
            while (it.hasNext()) {
                s = it.next();
                if (Integer.parseInt(s) >= 2001) {
                    cuenta++;
                }
            }
            boolean respuesta = true;
            if (cb_respuesta.getSelectedIndex() == 0) {
                respuesta = true;
            } else if (cb_respuesta.getSelectedIndex() == 1) {
                respuesta = false;
            }

            HashMap<String, String> examen = new HashMap<>();
            examen.put("titulo ", tf_titulo.getText());
            examen.put("descripcion", tf_descripcion.getText());
            examen.put("IdClase", ((String) cb_elegirClase.getSelectedItem()).charAt(4) + "");
            examen.put("respuesta", respuesta + "");
            jedis.hmset(cuenta + "", examen);
            JOptionPane.showMessageDialog(null, "Pregunta creada con exito");

            tf_titulo.setText("");
            tf_descripcion.setText("");
            cb_elegirClase.setSelectedIndex(0);
            cb_respuesta.setSelectedIndex(0);
            contClases++;
            tf_idPregunta.setText(contClases + "");
        }
    }//GEN-LAST:event_jb_crearPreguntaMouseClicked

    private void cb_elegirClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_elegirClaseItemStateChanged
        // TODO add your handling code here:
        Jedis jedis = new Jedis("localhost", 6379);

        Set<String> names = jedis.keys("*");
        java.util.Iterator<String> it = names.iterator();
        String s = "";
        int cuenta = 0;

        while (it.hasNext()) {
            s = it.next();

            HashMap<String, String> val = (HashMap<String, String>) jedis.hgetAll(s);

            //System.out.println("todo "+jedis.hgetAll(s));
            if (Integer.parseInt(s) >= 2001) {
                if (val.get("IdClase").charAt(0) == ((String) cb_elegirClase.getSelectedItem()).charAt(4)) {
                    cuenta++;
                }
            }

        }
        jl_cantPreguntas.setText(cuenta + "");
    }//GEN-LAST:event_cb_elegirClaseItemStateChanged
    int contClases = 2001;
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        Jedis jedis = new Jedis("localhost", 6379);

        Set<String> names = jedis.keys("*");
        java.util.Iterator<String> it = names.iterator();
        String s = "";
        contClases = 2001;

        while (it.hasNext()) {
            s = it.next();

            if (Integer.parseInt(s) >= 2001) {
                contClases++;

            }
        }
        tf_idPregunta.setText(contClases + "");
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void cb_elegirClaseEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_elegirClaseEItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_elegirClaseEItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoTBDD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoTBDD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoTBDD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoTBDD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoTBDD2().setVisible(true);
            }
        });
    }

    public void subirBase(int idE, String cadena) {
        Jedis jedis = new Jedis("localhost", 6379);
        jedis.set("" + idE, cadena);
    }

    public void tokenizarAlumnos() {

        for (int i = 0; i < users.size(); i++) {
            String[] arAlumnos = users.get(i).split("\\+");
            if (Integer.parseInt(arAlumnos[0]) >= 1 && Integer.parseInt(arAlumnos[0]) <= 100) {//clase
                clases.add(new Clase(Integer.parseInt(arAlumnos[0]), arAlumnos[1]));
            } else if (Integer.parseInt(arAlumnos[0]) >= 1001 && Integer.parseInt(arAlumnos[0]) <= 2000) {//examen

                examenes.add(new Examen(Integer.parseInt(arAlumnos[0]), Integer.parseInt(arAlumnos[1]), Integer.parseInt(arAlumnos[2])));

            } else if (Integer.parseInt(arAlumnos[0]) >= 2001) {//pregunta
                boolean val;
                if (arAlumnos[2].equals("V")) {
                    val = true;
                } else {
                    val = false;
                }
                preguntas.add(new Preguntas(Integer.parseInt(arAlumnos[0]), arAlumnos[1], arAlumnos[2], Integer.parseInt(arAlumnos[3]), val));

            } else {//alumno
                Alumno alumno = new Alumno(Integer.parseInt(arAlumnos[0]), arAlumnos[1], arAlumnos[2], arAlumnos[3]);
                if (users.get(i).contains("*")) {
                    if (users.get(i).contains("%")) {
                        String[] arExams = arAlumnos[arAlumnos.length - 1].split("\\%");

                        for (int j = 0; j < arExams.length; j++) {
                            String[] parts = arExams[j].split("\\*");

                            alumno.addExam(new Examen(Integer.parseInt(parts[0]), Integer.parseInt(parts[1])));
                        }
                    } else {
                        String[] arExams = arAlumnos[arAlumnos.length - 1].split("\\*");
                        for (int j = 0; j < arExams.length - 1; j++) {
                            alumno.addExam(new Examen(Integer.parseInt(arExams[0]), Integer.parseInt(arExams[1])));
                        }

                    }
                }
                alumnos.add(alumno);
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_clasesC;
    private javax.swing.JComboBox<String> cb_elegirClase;
    private javax.swing.JComboBox<String> cb_elegirClaseE;
    private javax.swing.JComboBox<String> cb_respuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_crearClase;
    private javax.swing.JButton jb_crearPregunta;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_loginL;
    private javax.swing.JButton jb_registrar;
    private javax.swing.JButton jb_registrarR;
    private javax.swing.JButton jb_regresarL;
    private javax.swing.JButton jb_regresarR;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_estudiante;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_registrar;
    private javax.swing.JLabel jl_cantPreguntas;
    private javax.swing.JPasswordField pf_contraL;
    private javax.swing.JPasswordField pf_passR;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_idClaseC;
    private javax.swing.JTextField tf_idPregunta;
    private javax.swing.JTextField tf_loginR;
    private javax.swing.JTextField tf_nameR;
    private javax.swing.JTextField tf_nombreClaseC;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_usuarioL;
    // End of variables declaration//GEN-END:variables
    ArrayList<Alumno> alumnos = new ArrayList();
    ArrayList<Clase> clases = new ArrayList();
    ArrayList<Examen> examenes = new ArrayList();
    ArrayList<Preguntas> preguntas = new ArrayList();

}
